Anya/getting sql
SimpleDataLabsInc/prophecy-docs pull request #146
Opened 2023-06-02 21:32 UTC by atbida

2023-06-06 04:43 UTC, several27 requested changes

2023-06-06 04:43 UTC, several27 commented on docs/low-code-sql/getting-started-with-low-code-sql.md
> +---
@atbida Could we move this under the `Getting Started` section?

2023-06-06 04:43 UTC, several27 commented on docs/low-code-sql/getting-started-with-low-code-sql.md
> +---
We can have two sections there - `Spark with Databricks` & `SQL with Databricks`

2023-06-06 04:43 UTC, several27 commented on docs/low-code-sql/getting-started-with-low-code-sql.md
> +
Would you mind writing here a little bit of an introduction?

2023-06-06 04:43 UTC, several27 commented on docs/low-code-sql/getting-started-with-low-code-sql.md
> +
Also, are we going to be able to share the video here?

2023-06-06 04:43 UTC, several27 commented on docs/low-code-sql/getting-started-with-low-code-sql.md
> +</div></div>
<img width="1061" alt="Screenshot 2023-06-05 at 9 41 59 PM" src="https://github.com/SimpleDataLabsInc/prophecy-docs/assets/3248329/20a464db-4947-417e-a7c1-b63d7944b7f4">

There seems to be something off with the rendering here. Wistia logo shows up at the top

2023-06-06 04:43 UTC, several27 commented on docs/low-code-sql/img/7-2-build-model.mp4
What is this video used for @atbida? Let's remove if not, we should avoid large files on git :P

2023-06-06 21:59 UTC, several27 approved these changes

2023-06-07 16:59 UTC, keerthiprophecy approved these changes

2023-06-07 17:31 UTC, merged