Update dependencies doc
SimpleDataLabsInc/prophecy-docs pull request #487
Opened 2024-12-20 15:21 UTC by kathweinschenkprophecy

2024-12-20 15:22 UTC, kathweinschenkprophecy commented on docs/Spark/extensibility/dependencies.md
> +| Version/Package/Coordinates | For Package Hub dependencies, input the package version. For Scala, use the Maven coordinates in the `groupId:artifcatId:version` format. For example, use `org.postgre
I don't see the option to choose "Package Hub" when installing a **Pipelines** dependency. Can I provide a reason why?

2024-12-20 15:22 UTC, kathweinschenkprophecy commented on docs/Spark/extensibility/dependencies.md
> +## Build System template
Do we want users to edit the template? Or do we want them to ignore it

2024-12-20 15:23 UTC, kathweinschenkprophecy commented
To do:

- Add screenshots
- Clean up old screenshots
- Validate Livy/EMR dependency limitation
- Libs redirect

2025-01-02 17:45 UTC, neontty requested changes

2025-01-02 17:45 UTC, neontty commented on docs/Spark/extensibility/dependencies.md
> +**pom.xml** file. If you're using Python, dependencies are saved in the **setup.py** file.
we should put a tooltip to recommend that users store dependencies at a Project level whenever possible to improve the experience of interactive development. This will minimize the time spent connecting to clusters when switching between pipelines in the IDE.

2025-01-02 17:45 UTC, neontty commented on docs/Spark/extensibility/dependencies.md
> +| Version/Package/Coordinates | For Package Hub dependencies, input the package version. For Scala, use the Maven coordinates in the `groupId:artifcatId:version` format. For example, use `org.postgre
you may be using a project that has Prophecy Managed Git. I believe that may not allow you to use packagehub. we can discuss more over chat

2025-01-02 17:45 UTC, neontty commented on docs/Spark/extensibility/dependencies.md
> +## Build System template
the users can edit the template  if there are specific items that they require during the build process. For example if they want to add the JaCoCo plugin to the build process for coverage report generation

2025-01-02 20:20 UTC, kathweinschenkprophecy commented on docs/Spark/extensibility/dependencies.md
> +| Version/Package/Coordinates | For Package Hub dependencies, input the package version. For Scala, use the Maven coordinates in the `groupId:artifcatId:version` format. For example, use `org.postgre
I still don't see it on a project using external git. Though, it doesn't really matter for these docs at the moments... we can return to the question

2025-01-02 21:54 UTC, neontty requested changes
just realized that there is 1 more section we need to add: 

Scala Dependencies in Pyspark: how do python projects track scala dependencies

We need to note how that gets tracked in pbt_project.yaml  and have a hyperlink to the PBT (needs to be written) page which describes the option to build python WHLs with a dummy POM.xml file ... for now we can just hyperlink to PBT main page. 

I can provide more details on this tomorrow

2025-01-06 22:56 UTC, neontty commented
additional info for new section: 

  When deploying pipelines in the WHL format we must consider dependencies both in Python and Scala.  These Scala jars are used by spark applications in the underlying jvm ( even in pyspark applications).  The WHL format inherently records python dependencies, however there is no industry standard for WHL files to specify non-python dependencies (jar files). As a result we have enhanced PBT to record the Scala dependency information and store it in the WHL file


recently we made an improvement to the prophecy-build-tool which allows you to generate any Scala dependencies of pyspark pipelines as `pom.xml` and a flat file called `MAVEN_COORDINATES`
 
just run pbt once on your project like so: 
 
`pbt build-v2 --add-pom-xml-python --path .` 
 
and it will generate those files and add them to the WHL under `{package_name}-1.0.data/data/`
(note: set the environment variable `SPARK_VERSION`  with a valid spark version that ends in a 0 [3.3.0,3.4.0,3.5.0] which corresponds to the spark version you plan to use in the execution environment. Otherwise there is no context for PBT to generate the spark version part of the maven coordinate and a string `{{REPLACE_ME}}` will be used instead).

2025-01-07 20:52 UTC, neontty commented
@kathweinschenkprophecy , I made a few changes; mostly pointing out that this is **only** necessary if the user did not create a Job in the Prophecy UI and is deploying the WHL file manually (not using `pbt deploy` or `pbt deploy-v2`) . 

Please go ahead and correct anything if I made any bad suggestions.

2025-01-07 20:53 UTC, neontty approved these changes

2025-01-07 21:24 UTC, merged