added docs for config 2.0 and search
SimpleDataLabsInc/prophecy-docs pull request #62
Opened 2022-09-15 09:11 UTC by jainabhinav

2022-09-16 23:52 UTC, slyons requested changes

2022-09-16 23:52 UTC, slyons commented on docs/low-code-spark/configuration.md
> +Runtime Spark configurations as name-value pairs. The name-value pairs will be set inside the Spark runtime configurations as `spark.conf.set(name, value)`
"Runtime Spark configurations" -> "Set runtime Spark configurations"

2022-09-16 23:52 UTC, slyons commented on docs/low-code-spark/configuration.md
> +Syntax for using configuration inside Gems:
Can we turn this into a visual example with a Code block? We might have to break this up based on the use case a bit more. The user won't understand what "visual language SQL" vs "visual language Scala" means.

2022-09-16 23:52 UTC, slyons commented on docs/low-code-spark/configuration.md
> +In the below image `amounts` -> `expr('$test_expression')` is coming from configuration type defined as `Spark-expression`
Add numbers/letters to the image to draw the reader's attention to them, then put a table under the image with the explanation. See the Concepts section of documents for some examples.

2022-09-16 23:52 UTC, slyons commented on docs/low-code-spark/configuration.md
> +Config can also be used to refer to paths. This type of configuration comes in handy in situation where we have dev, qa and prod data.
"dev" -> "`DEV`", for dev qa and prod

2022-09-20 11:22 UTC, rishabh-sudan approved these changes

2022-09-20 12:22 UTC, merged